# Ação do GitHub para gerar um gráfico de contribuição animado (snake)

# Nome da Ação
name: Generate Snake

# Controla quando a ação corre
on:
  # Corre a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você corra manualmente pela aba "Actions"
  workflow_dispatch:
  
  # Também corre quando você faz push para a branch main
  push:
    branches:
      - main

# Define o trabalho a ser feito
jobs:
  # Um único trabalho chamado "build"
  build:
    # Corre num servidor Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      # 1. Copia o seu repositório para o servidor
      - name: Clone repo
        uses: actions/checkout@v3

      # 2. Gera os ficheiros da "cobra" numa pasta ./dist/
      - name: Generate the snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          # Pega o seu username automaticamente
          github_user_name: ${{ github.repository_owner }}
          
          # Gera estes ficheiros de saída (SVG)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Faz o "deploy" desses ficheiros para a branch "output"
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # A branch para onde enviar os ficheiros gerados
          target_branch: output
          # O diretório que contém os ficheiros
          build_dir: dist
        env:
          # Token secreto para permitir que a Ação escreva no seu repositório
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
